Repository rainbowgon/opentheDoor-crawling, pull requests merged in 2023-11, with the labels that each got.

#4 [feat] 엘라스틱 서치 인덱스 구현
  .gitignore
  crawling.js
  package-lock.json
  package.json
Labels: 💡 feature

#6 [env] 서버 초기 설정
  .gitignore
  README.md
  app.js
  crawling.js
  index.html
  package-lock.json
  package.json
  public/informationCrawlers/masterkey/crawler.js
  public/reservationCrawlers/masterkey/crawler.js
Labels: 🏗 env, 🛠 refactor, 🏢 venue

#8 [refactor] 전체 코드 리팩토링
  .env.local
  .gitignore
  app.js
  modules/common/elasticSearch/createIndex.js
  modules/common/elasticSearch/esIndexObject.js
  modules/common/elasticSearch/insertData.js
  modules/common/tools/config.js
  modules/common/tools/fetch.js
  modules/informationCrawlers/masterkey/crawler.js
  modules/informationCrawlers/masterkey/run.js
  modules/reservationCrawlers/masterkey/crawler.js
  package-lock.json
  package.json
  public/informationCrawlers/masterkey/crawler.js
Labels: 🛠 refactor, 🏢 venue, ⏰ time

#10 [refactor] common 메소드 분리
  modules/common/elasticSearch/createIndex.js
  modules/common/elasticSearch/insertData.js
  modules/common/mongodb/mongodbInsertData.js
  modules/common/tools/createInsertTask.js
  modules/common/tools/hashCreator.js
  modules/informationCrawlers/masterkey/crawler.js
Labels: 🛠 refactor

#12 [fix] Redis 오류 수정 및 로직 수정
  .env.local
  modules/common/config/env.js
  modules/common/config/masterkey.js
  modules/common/elasticSearch/createIndex.js
  modules/common/elasticSearch/insertData.js
  modules/common/tools/taskCreator.js
  modules/informationCrawlers/masterkey/crawler.js
  modules/informationCrawlers/masterkey/run.js
  modules/reservationCrawlers/masterkey/crawler.js
  modules/reservationCrawlers/masterkey/run.js
Labels: 🚨 fix

#14 [fix] 변수 이름 변경
  modules/informationCrawlers/masterkey/crawler.js
Labels: 🚨 fix

#16 [feat] 크롤링 데이터 필드 추가
  modules/common/elasticSearch/insertData.js
  modules/common/mongodb/mongodbInsertData.js
  modules/informationCrawlers/masterkey/crawler.js
Labels: 💡 feature

#18 [fix] 필드명 변경
  modules/common/elasticSearch/insertData.js
  modules/common/mongodb/mongodbInsertData.js
Labels: 🚨 fix

#20 [fix] 지점명을 "브랜드명 + 지점명"으로 변경
  modules/common/elasticSearch/insertData.js
  modules/common/mongodb/mongodbInsertData.js
Labels: 🚨 fix, 🏢 venue

#23 [fix] 데이터 형식 수정
  .env.local
  modules/common/config/env.js
  modules/common/elasticSearch/insertData.js
  modules/common/mongodb/mongodbInsertData.js
  modules/common/tools/geocoding.js
Labels: 🚨 fix, 🏢 venue

#24 [feat] 경도, 위도 값 저장 완료
  modules/common/elasticSearch/insertData.js
  modules/common/mongodb/mongodbInsertData.js
  modules/common/tools/geocoding.js
  modules/informationCrawlers/masterkey/crawler.js
  package-lock.json
  package.json
Labels: 💡 feature, 🏢 venue

#26 [feat] S3 업로드 구현
  .gitignore
  modules/common/config/env.js
  modules/common/mongodb/mongodbInsertData.js
  modules/common/tools/imageUploader.js
  modules/informationCrawlers/masterkey/crawler.js
  package-lock.json
  package.json
Labels: 💡 feature

#29 [infra/feat] 젠킨스를 이용한 CI/CD
  Dockerfile
  scripts/deploy.sh
Labels: 💡 feature, 🛰 infra

#32 [infra/fix] 현재 위치의 파일들을 build
  scripts/deploy.sh
Labels: 🚨 fix, 🛰 infra

#34 [infra/fix] Dockerfile 수정
  Dockerfile
Labels: 🚨 fix, 🛰 infra

#36 [fix] 크롤링 과정에서 레디스를 사용하는 부분 삭제
  modules/common/elasticSearch/insertData.js
  modules/common/mongodb/mongodbInsertData.js
  modules/common/tools/geocoding.js
  modules/common/tools/imageUploader.js
  modules/informationCrawlers/masterkey/crawler.js
  modules/informationCrawlers/masterkey/run.js
Labels: 🚨 fix, 🏢 venue

#37 [fix] 권장 인원 데이터 크롤링 중 에러 수정
  modules/common/elasticSearch/insertData.js
  modules/common/mongodb/mongodbInsertData.js
  modules/informationCrawlers/masterkey/crawler.js
Labels: 🚨 fix

#40 [fix] crawler.js 에러 수정
  modules/informationCrawlers/masterkey/crawler.js
Labels: 🚨 fix

#42 [infra/fix] puppeteer를 위한 Dockerfile 수정
  Dockerfile
  modules/common/config/env.js
  modules/common/elasticSearch/createIndex.js
  modules/common/elasticSearch/insertData.js
  modules/common/mongodb/mongodbInsertData.js
  modules/informationCrawlers/masterkey/crawler.js
  modules/informationCrawlers/masterkey/run.js
  scripts/deploy.sh
Labels: 🚨 fix, 🛰 infra

#44 [fix] merge 중 발생한 문제 해결
  modules/informationCrawlers/masterkey/crawler.js
Labels: 🚨 fix

#46 [feat] url 필드 추가
  modules/common/elasticSearch/insertData.js
  modules/common/mongodb/mongodbInsertData.js
  modules/informationCrawlers/masterkey/crawler.js
Labels: 💡 feature

#47 [feat] url 필드 추가
  modules/common/elasticSearch/insertData.js
  modules/common/mongodb/mongodbInsertData.js
  modules/informationCrawlers/masterkey/crawler.js
Labels: 💡 feature

#50 [feat] 시간대 정보 저장
  app.js
  modules/common/tools/taskCreator.js
  modules/reservationCrawlers/masterkey/crawler.js
  modules/reservationCrawlers/masterkey/run.js
  package-lock.json
  package.json
  src/common/config/env.js
  src/common/config/masterkey.js
  src/common/elasticSearch/createIndex.js
  src/common/elasticSearch/esIndexObject.js
  src/common/elasticSearch/insertData.js
  src/common/mongodb/mongodbInsertData.js
  src/common/redis/redisTaskCreator.js
  src/common/tools/browser.js
  src/common/tools/class.js
  src/common/tools/enum.js
  src/common/tools/flatten.js
  src/common/tools/geocoding.js
  src/common/tools/hashCreator.js
  src/common/tools/imageUploader.js
  src/informationCrawlers/masterkey/crawler.js
  src/informationCrawlers/masterkey/run.js
  src/timeCrawlers/masterkey/crawler.js
  src/timeCrawlers/masterkey/run.js
Labels: 💡 feature, ⏰ time

#52 [fix] REDIS 설정 가져오기
  src/common/config/env.js
  src/timeCrawlers/masterkey/run.js
Labels: 🚨 fix, 🏢 venue

#54 [feat] 빈자리 알림 구현
  app.js
  package-lock.json
  package.json
  src/common/config/env.js
  src/common/redis/redisTaskCreator.js
  src/common/tools/sendNotification.js
  src/timeCrawlers/masterkey/crawler.js
  src/timeCrawlers/masterkey/run.js
Labels: 💡 feature, ⏰ time

#56 [fix] 타임 라인 해시 키 정책 수정
  src/common/tools/hashCreator.js
  src/timeCrawlers/masterkey/crawler.js
Labels: 🚨 fix, ⏰ time

#58 [chore] 로그 출력 수정
  src/common/elasticSearch/insertData.js
  src/common/redis/redisTaskCreator.js
  src/timeCrawlers/masterkey/crawler.js
Labels: 🚨 fix, ⏰ time
